### PR TITLE
S3 client upload

### PR DESCRIPTION
**Pull request by des-des**
Yay it works

### CODE REVIEW

**Comment by jbesraa** [comment]
@des-des do you wanna fix travis or is it ok to merge?

**Comment by des-des** [comment]
@esraa will fix tests soon

**Comment by sohilpandya** [comment]
@des-des @esraajb where are the emails being directed to at this moment in time? Can we get the emails to go to a couple of places, including ours and the official one?

**Comment by des-des** [comment]
@sohilpandya tomorrow I am going to put a half day in.

  1. Fix this pull
  2. Set up email
  3. Make UI tweeks
  4. Do you think there is a chance we can drop the weekly email? I can do it if necessary

**Comment by sohilpandya** [comment]
Hi @des-des.

Thanks for the update. It'll be great to get the top 3 done as a priority and then see where we are, I'd be great to have 4. done as well even if its not a csv and a simple list instead to start with. 

keep me updated as to where you get to. 👍

**Comment by des-des** [comment]
Okay, it was a massive chore, but fixed tests so now we can get on with the final tweeks (yay)

**Pull request merged**
